mutation MyMutation($objects: [keterangan_insert_input!] = {}) {
  insert_keterangan(objects: $objects) {
    returning {
      id
      id_anggota
      pelajaran
      nilai
      status
    }
  }
}

{
  "objects": [
    {
      "id_anggota": 3,
      "pelajaran": "Sistem Informasi",
      "nilai": 90,
      "status": true
    },
    {
      "id_anggota": 3,
      "pelajaran": "React",
      "nilai": 55,
      "status": false
    }
  ]
}